export interface statistics {
    name: string;
    content: any;
    s: number;
    descpription: any;
}


export const StatsBarChart: statistics[] =
    [
        {
            "name": "PRODUCT",
            "content": [
                "Fifth",
                "B-52s"
            ],
            "s": 2,
            "descpription": "Objects, vehicles, foods, etc. (not services)"
        },
        {
            "name": "CARDINAL",
            "content": [
                "six",
                "three",
                "two",
                "two",
                "nearly half",
                "Thousands",
                "1,400",
                "hundreds and hundreds",
                "25 million",
                "millions",
                "one",
                "thousands",
                "Nine million",
                "nine million",
                "Five million",
                "3.5 million",
                "10 million",
                "million",
                "one",
                "30",
                "10 million",
                "3.5 million",
                "one",
                "one",
                "two",
                "104",
                "33,000",
                "33,000",
                "one",
                "zero",
                "zero",
                "zero",
                "zero",
                "one",
                "6",
                "one",
                "thousands",
                "six",
                "one",
                "four",
                "tens of thousands",
                "one",
                "two and three and four",
                "two",
                "two",
                "thousands",
                "thousands",
                "Thousands",
                "thousands",
                "thousands",
                "almost 4,000",
                "almost 4,000",
                "two",
                "3,000",
                "4,000",
                "five",
                "one-half",
                "2,200",
                "500",
                "Five hundred",
                "500",
                "2,200",
                "500",
                "two",
                "two",
                "one",
                "14",
                "15",
                "one",
                "zero",
                "one",
                "two",
                "one",
                "50",
                "16,500",
                "one",
                "one",
                "10,000",
                "two",
                "one",
                "28",
                "two",
                "number two",
                "30",
                "one",
                "two",
                "one",
                "9/11",
                "28",
                "one",
                "One",
                "one",
                "112",
                "one",
                "One",
                "one",
                "hundreds of millions",
                "800",
                "800",
                "1,800",
                "one",
                "one",
                "one",
                "two",
                "ten",
                "millions and millions",
                "Four",
                "One",
                "12",
                "two",
                "one",
                "Number two",
                "33,000",
                "two",
                "33,000",
                "one-fifth",
                "millions",
                "millions",
                "110",
                "eight",
                "33,000",
                "33,000",
                "three or three or four or five",
                "33,000",
                "39,000",
                "33,000",
                "35,000",
                "15,000",
                "one",
                "three",
                "20 million",
                "170 million",
                "one",
                "two",
                "three",
                "four",
                "half",
                "20 million",
                "one",
                "two",
                "3.3 million",
                "one",
                "two",
                "14",
                "hundreds of thousands",
                "the tens of thousands",
                "hundreds of thousands",
                "10,000",
                "65,000",
                "16,500",
                "millions",
                "one",
                "two",
                "One",
                "one",
                "One",
                "one",
                "two",
                "millions",
                "zero",
                "zero",
                "zero",
                "zero",
                "three",
                "32",
                "Eight million",
                "Hundreds of thousands",
                "Hundreds of thousands",
                "Four hundred",
                "136 million",
                "400",
                "at least 100",
                "hundreds of thousands",
                "about 250,000",
                "one",
                "three",
                "200",
                "21",
                "200",
                "20,000",
                "30,000",
                "one",
                "half",
                "half",
                "3",
                "600",
                "600",
                "600",
                "almost 25 million",
                "23 million",
                "Nine million",
                "Five million",
                "nine",
                "nine",
                "20",
                "one",
                "one",
                "one",
                "millions",
                "one",
                "One",
                "one",
                "Six",
                "two",
                "at least one",
                "two or three",
                "20",
                "two",
                "33,000",
                "millions",
                "dozens",
                "33,000",
                "two",
                "three",
                "one",
                "two or three",
                "two",
                "two",
                "four",
                "thousands",
                "16,500",
                "11 million",
                "4 million",
                "15 million",
                "millions",
                "millions",
                "millions",
                "17",
                "thousands and thousands",
                "1,800",
                "1,800",
                "17",
                "17",
                "17",
                "17",
                "ten",
                "200",
                "21",
                "21",
                "two-thirds",
                "10 million",
                "3.5 million",
                "One",
                "Three",
                "two-thirds",
                "one",
                "about 25 million",
                "12",
                "32",
                "nine",
                "33,000",
                "four",
                "one",
                "hundreds",
                "four",
                "11 million",
                "about half",
                "one",
                "Half",
                "millions",
                "Millions",
                "Millions",
                "one",
                "one",
                "one",
                "two",
                "dozens",
                "several thousand",
                "quarter",
                "million",
                "tens of thousands",
                "millions",
                "millions",
                "dozens",
                "32",
                "less than zero",
                "one",
                "one",
                "ten",
                "three",
                "three",
                "millions",
                "One"
            ],
            "s": 283,
            "descpription": "Numerals that do not fall under another type"
        },
        {
            "name": "ORDINAL",
            "content": [
                "first",
                "second",
                "First",
                "eighth",
                "first",
                "second",
                "first",
                "first",
                "First",
                "Second",
                "Third",
                "Fifth",
                "third",
                "third",
                "first",
                "first",
                "second",
                "first",
                "First",
                "first",
                "first",
                "First",
                "first",
                "first",
                "first",
                "first",
                "first",
                "first",
                "first",
                "first",
                "first",
                "first",
                "first",
                "first",
                "first",
                "first",
                "first",
                "first",
                "First",
                "first",
                "First",
                "First",
                "first",
                "10th",
                "12th",
                "first",
                "first",
                "first",
                "first",
                "first",
                "first",
                "First",
                "second",
                "second",
                "first",
                "first",
                "first",
                "first",
                "First",
                "first",
                "third",
                "first",
                "first",
                "First",
                "secondly",
                "first",
                "second",
                "second",
                "second",
                "second",
                "First",
                "second",
                "first",
                "second",
                "second",
                "second",
                "second",
                "second",
                "second",
                "second",
                "second",
                "second",
                "second",
                "second",
                "second",
                "second",
                "second",
                "second",
                "first",
                "first",
                "First",
                "First",
                "first",
                "first",
                "first",
                "first",
                "first",
                "first",
                "first",
                "first",
                "first",
                "First",
                "first",
                "first",
                "Secondly",
                "first",
                "first",
                "first",
                "first"
            ],
            "s": 109,
            "descpription": "\"first\", \"second\", etc."
        },
        {
            "name": "QUANTITY",
            "content": [
                "a half a billion",
                "400 pounds",
                "six-foot"
            ],
            "s": 3,
            "descpription": "Measurements, as of weight or distance"
        },
        {
            "name": "MONEY",
            "content": [
                "$14 million",
                "$20 trillion",
                "$13 trillion",
                "$5 trillion",
                "$20 trillion",
                "$5 trillion",
                "a penny",
                "$5 trillion",
                "$1.3 trillion",
                "billions and billions of dollars",
                "$2.5 trillion",
                "$2.5 trillion",
                "$5 trillion",
                "$4 billion",
                "$694 million",
                "$694 million",
                "almost $800 billion",
                "about $650 million",
                "650",
                "$3.9 billion",
                "650",
                "650",
                "$20 trillion",
                "$20 trillion",
                "$20 trillion",
                "$6 trillion",
                "6, $6 trillion",
                "hundreds of millions of dollars",
                "$20 trillion",
                "$400 million",
                "$1.7 billion",
                "billions and billions of dollars",
                "$150 billion",
                "hundreds of millions of dollars",
                "$200 million",
                "$150 billion",
                "almost $800 billion",
                "$800 billion",
                "850,000",
                "almost $20 trillion",
                "hundreds of millions of dollars",
                "hundreds of millions of dollars",
                "less than $250,000",
                "billion-dollar",
                "a million dollars",
                "above $5 million",
                "$916 million",
                "$916 million",
                "$150 billion",
                "$1.7 billion",
                "tens of millions",
                "$300 billion",
                "$200 billion",
                "$13 trillion",
                "more than $100 million",
                "more than $100 million",
                "61",
                "$250 million",
                "$100 million",
                "$10 million",
                "$20 million or $25 million or $30 million",
                "$30 million",
                "$20 trillion",
                "millions of dollars",
                "millions and millions",
                "225,000",
                "$6 trillion",
                "less than $125,000",
                "$20 trillion",
                "up to $20 trillion",
                "$2.5 trillion",
                "250,000",
                "a penny",
                "$20 trillion",
                "$300 billion",
                "$200 billion",
                "a penny",
                "$6 billion",
                "$6 billion",
                "$6 billion",
                "$6 billion",
                "$14 million",
                "$1 million",
                "$1 million",
                "1500",
                "$25 million",
                "$30 million",
                "a penny",
                "hundreds of millions of dollars",
                "hundreds of millions of dollars",
                "$150 billion",
                "$1.7 billion",
                "$1.7 billion",
                "100,000",
                "a penny",
                "$20 trillion"
            ],
            "s": 96,
            "descpription": "Monetary values, including unit"
        },
        {
            "name": "PERCENT",
            "content": [
                "35 percent to",
                "5 percent",
                "the other 95 percent",
                "16 percent",
                "30 percent",
                "50 percent",
                "50 percent",
                "40 percent",
                "approximately 73 percent",
                "68 percent",
                "59 percent",
                "71 percent",
                "90 percent",
                "100 percent",
                "550 percent",
                "550 percent",
                "35 percent to 15 percent",
                "7 percent",
                "1 percent",
                "45 percent",
                "45 percent",
                "67 percent",
                "33 percent",
                "550%",
                "1%",
                "4%",
                "8%",
                "7%",
                "1%",
                "100%",
                "90%",
                "90%",
                "100%",
                "100%",
                "77%",
                "86%",
                "105%",
                "1%",
                "1%",
                "4%",
                "higher than 4%",
                "5%",
                "6%",
                "60%",
                "60%",
                "70%",
                "80%",
                "over 100%"
            ],
            "s": 48,
            "descpription": "Percentage, including \"%\""
        },
        {
            "name": "DATE",
            "content": [
                "today",
                "years",
                "Today",
                "November 8th",
                "1975",
                "30 years",
                "years",
                "years",
                "eight years ago",
                "the 1930s",
                "2006",
                "the 21st century",
                "the last eight years",
                "230 years'",
                "almost eight years",
                "seven-and-a-half years",
                "30 years",
                "30 years",
                "30 years",
                "the 1990s",
                "the 1990s",
                "30 years",
                "26 years",
                "40",
                "tomorrow",
                "the end of this evening",
                "2008",
                "2009",
                "decades",
                "today",
                "this past year",
                "15 or 20 years ago",
                "15 years",
                "almost every year",
                "40 years",
                "39",
                "40 years",
                "a couple of years",
                "a lot of years",
                "a year ahead",
                "decades",
                "the first day",
                "today",
                "today",
                "January 1st",
                "years",
                "January 1st",
                "1991",
                "25 years",
                "last week",
                "a few weeks ago",
                "four years",
                "up to 100 years",
                "five years",
                "the last couple of weeks",
                "years",
                "this past week",
                "2011",
                "2012",
                "'13",
                "January",
                "the last week",
                "1973",
                "just last week",
                "a 21st century",
                "next week",
                "the last 10 years",
                "10 years old",
                "the year",
                "the last year",
                "about four months ago",
                "2002",
                "the other day",
                "'04",
                "2002",
                "the other day",
                "weeks",
                "The other day",
                "40 years ago",
                "10 years",
                "the other day",
                "the last 10 years",
                "this year",
                "Earlier this month",
                "another four years",
                "this November",
                "today",
                "October 9th",
                "October 19th",
                "October 4th",
                "today",
                "November",
                "the last year-and-a-half",
                "just three years ago",
                "Last year",
                "weekly",
                "today",
                "Friday",
                "a number of years ago",
                "11 years ago",
                "June",
                "Friday",
                "nearly a week",
                "four years later",
                "2016",
                "age 59",
                "12 years old",
                "11 years ago",
                "weeks",
                "just two weeks ago",
                "last week",
                "year-long",
                "days",
                "the age of 26",
                "years",
                "December",
                "this week",
                "today",
                "today",
                "4-year-old",
                "the last few days",
                "this years ago",
                "the years",
                "30 years",
                "20 years",
                "the last month",
                "1995",
                "years",
                "years",
                "30 years",
                "years",
                "30 years this and 30 years",
                "30 years",
                "every year",
                "9/11",
                "eight years",
                "30 years",
                "5-year-old",
                "the past few weeks",
                "Just days ago",
                "this week",
                "three weeks",
                "four weeks",
                "the next four to six weeks",
                "weeks",
                "weeks",
                "years",
                "25 years",
                "the 30 years",
                "10 years old",
                "last month",
                "45 years",
                "another four years",
                "2008",
                "the days",
                "9/11",
                "1929",
                "1,000 years",
                "the last seven years",
                "the 21st century",
                "30 years",
                "every single day",
                "October 19th",
                "2016",
                "the next quarter century",
                "last year",
                "18 wonderful years",
                "every year",
                "the ninth month",
                "the ninth month",
                "the final day",
                "a period of years",
                "last week",
                "the other day",
                "a few weeks ago",
                "years",
                "the first 100 days",
                "2006",
                "the century",
                "the last years",
                "a year ago",
                "2009",
                "1949",
                "July",
                "10-year",
                "Last week",
                "the end of last week",
                "the last year",
                "20, 25 years ago",
                "30 years",
                "the last 15, 20 years",
                "30 years",
                "the 30 years",
                "the 1970s",
                "the 1980s",
                "the 1990s",
                "30 years",
                "thirty years",
                "years",
                "this last couple of weeks",
                "today",
                "today",
                "five years",
                "the last weeks",
                "the last ten days",
                "2009",
                "the other day",
                "many years",
                "today",
                "Sunday",
                "Today",
                "November 8th",
                "three years in a row",
                "240 years",
                "About three months ago",
                "three months",
                "many years ago",
                "years ago",
                "two years ago",
                "three years ago",
                "the coming years",
                "today",
                "the first day",
                "4-year-old",
                "three weeks ago",
                "the next ten years",
                "the next ten years",
                "many decades",
                "decades",
                "1987",
                "years",
                "the 2020s",
                "the 2030s",
                "the year",
                "Next year",
                "four years",
                "four more years",
                "election day",
                "November 8",
                "20 days"
            ],
            "s": 241,
            "descpription": "Absolute or relative dates or periods"
        },
        {
            "name": "TIME",
            "content": [
                "evening",
                "tonight",
                "tonight",
                "90-minute",
                "15 minutes",
                "tonight",
                "up to two minutes",
                "tonight",
                "tonight",
                "up to two minutes",
                "30 seconds",
                "15-minute",
                "two-minute",
                "two minutes",
                "two minutes",
                "two minutes",
                "tonight",
                "two minutes",
                "two minutes",
                "two minutes",
                "one night",
                "20 seconds",
                "tonight",
                "two minutes",
                "two minutes",
                "a minute",
                "two minutes",
                "two minutes",
                "two minutes",
                "two minutes",
                "Twenty seconds",
                "a minute",
                "a minute",
                "11 hours",
                "10 seconds",
                "tonight",
                "this evening",
                "tonight",
                "two minutes",
                "two minutes",
                "the last 48 hours",
                "tonight",
                "just 48 hours",
                "two minutes",
                "tonight",
                "tonight",
                "tonight",
                "two minutes",
                "tonight",
                "39 minutes",
                "One second",
                "tonight",
                "tonight",
                "tonight",
                "two minutes",
                "about 25 seconds",
                "two minutes",
                "evening",
                "two minutes",
                "two minutes",
                "two minutes",
                "two minutes",
                "two minutes",
                "two minutes",
                "two minutes",
                "two minutes",
                "two minutes",
                "two minutes",
                "hours",
                "3 a.m. to 5 a.m.",
                "3 o\u2019clock in the morning",
                "a minute",
                "3 o\u2019clock in the morning",
                "3 o\u2019clock in the morning",
                "3 o\u2019clock in the morning",
                "two minutes",
                "two minutes",
                "two minutes",
                "Good night",
                "evening",
                "15-minute",
                "two minute",
                "two minutes",
                "about ten minutes",
                "two minutes",
                "this evening",
                "about 45 seconds",
                "about four minutes",
                "ten minutes",
                "two minutes",
                "two minutes",
                "two minutes",
                "a few minutes ago",
                "tonight",
                "two minutes",
                "one second",
                "tonight",
                "tonight"
            ],
            "s": 98,
            "descpription": "Times smaller than a day"
        },
        {
            "name": "LANGUAGE",
            "content": [
                "Aleppo",
                "Aleppo",
                "Aleppo"
            ],
            "s": 3,
            "descpription": "Any named language"
        },
        {
            "name": "LAW",
            "content": [
                "the Fifth Amendment",
                "the Second Amendment",
                "Article 5",
                "Constitution",
                "Roe v. Wade",
                "Roe v. Wade",
                "the Constitution of the United States",
                "the Second Amendment",
                "the Second Amendment",
                "the Second Amendment",
                "Roe v. Wade",
                "Roe v. Wade",
                "Roe v. Wade",
                "Roe v. Wade",
                "Roe v. Wade",
                "Roe v. Wade"
            ],
            "s": 16,
            "descpription": "Named documents made into laws."
        },
        {
            "name": "WORK_OF_ART",
            "content": [
                "Achieving Prosperity",
                "Stronger Together",
                "the King of Debt",
                "Miss Housekeeping",
                "Stronger Together",
                "Affordable Care Act",
                "Affordable Care Act",
                "Affordable Care Act",
                "Affordable Care Act",
                "Affordable Care Act",
                "The Celebrity Apprentice",
                "Make America Great Again",
                "Affordable Care Act"
            ],
            "s": 13,
            "descpription": "Titles of books, songs, etc."
        },
        {
            "name": "EVENT",
            "content": [
                "the Great Recession",
                "the Great Depression",
                "the Great Recession",
                "Holocaust",
                "the Great Depression",
                "World War II",
                "World War II"
            ],
            "s": 7,
            "descpription": "Named hurricanes, battles, wars, sports events, etc."
        },
        {
            "name": "PERSON",
            "content": [
                "Lester Holt",
                "Donald Trump",
                "Hillary Clinton",
                "Hillary Clinton",
                "Donald J. Trump",
                "Donald",
                "Clinton",
                "Donald Trump",
                "I. Donald",
                "Clinton",
                "Trump",
                "Lester",
                "Hillary",
                "Ronald Reagan",
                "Clinton",
                "Donald",
                "Donald",
                "Trump",
                "Lester",
                "Clinton",
                "Clinton",
                "Clinton",
                "Clinton",
                "Donald",
                "Donald",
                "Donald",
                "Trump",
                "Obama",
                "Hillary",
                "Donald",
                "Clinton",
                "Donald",
                "Obama",
                "Obama",
                "Obama",
                "Ronald Reagan",
                "Trump",
                "Douglas MacArthur",
                "Clinton",
                "Trump",
                "Trump",
                "Clinton",
                "Clinton",
                "Clinton",
                "Clinton",
                "Lester",
                "Trump",
                "Clinton",
                "Trump",
                "Clinton",
                "Clinton",
                "Trump",
                "Donald Trump",
                "Clinton",
                "Trump",
                "Kennedy",
                "Clinton",
                "Donald",
                "Trump",
                "Clinton",
                "Clinton",
                "Trump",
                "Clinton",
                "Barack Obama",
                "Giuliani",
                "Barack Obama",
                "Ferguson",
                "Clinton",
                "Clinton",
                "Clinton",
                "Donald",
                "Latino",
                "Donald",
                "Clinton",
                "Trump",
                "Bloomberg",
                "Trump",
                "Trump",
                "Trump",
                "Donald",
                "Trump",
                "Sidney Blumenthal",
                "Clinton",
                "Doyle",
                "Obama",
                "Solis Doyle",
                "Wolf Blitzer",
                "Clinton",
                "Sidney Blumenthal",
                "Clinton",
                "Donald",
                "Lester Holt",
                "Donald",
                "Barack Obama",
                "Michelle Obama",
                "Barack Obama",
                "Donald Trump's",
                "Trump",
                "Barack Obama",
                "Clinton",
                "Donald",
                "Vladimir Putin",
                "Putin",
                "Donald",
                "Putin",
                "Donald",
                "Trump",
                "Clinton",
                "Clinton",
                "Debbie Wasserman Schultz",
                "Bernie Sanders",
                "Obama",
                "Clinton",
                "Clinton",
                "bin Laden",
                "Trump",
                "Clinton",
                "Obama",
                "Clinton",
                "Clinton",
                "Donald",
                "Gadhafi",
                "George W. Bush",
                "Barack Obama",
                "Rahami",
                "Donald",
                "Donald",
                "Donald",
                "Trump",
                "Barack Obama",
                "Clinton",
                "Trump",
                "Howard Stern",
                "Neil Cavuto",
                "Sean Hannity",
                "Sean Hannity",
                "Sean Hannity",
                "Sean Hannity",
                "Sean Hannity",
                "Sean",
                "Sean Hannity",
                "Trump",
                "Clinton",
                "Clinton",
                "Clinton",
                "Clinton",
                "Donald",
                "Bush",
                "John Kerry",
                "Obama",
                "Donald",
                "Donald",
                "Obama",
                "Trump",
                "Clinton",
                "Kerry",
                "Bibi Netanyahu",
                "Clinton",
                "Clinton",
                "Donald",
                "Hillary",
                "Trump",
                "Trump",
                "Clinton",
                "Hillary",
                "Hillary",
                "Piggy",
                "Latina",
                "Donald",
                "Alicia Machado",
                "Trump",
                "Hillary",
                "Rosie O'Donnell",
                "Hillary",
                "Clinton",
                "Donald",
                "Trump",
                "Hillary",
                "Hillary Clinton",
                "Donald Trump",
                "Donald J. Trump",
                "Hillary Clinton",
                "Clinton",
                "Clinton",
                "Trump",
                "Trump",
                "Trump",
                "Trump",
                "Trump",
                "Trump",
                "Clinton",
                "Donald Trump",
                "Donald",
                "Twitter",
                "Universe",
                "Donald Trump",
                "Latinos",
                "Donald Trump",
                "Hillary",
                "Hillary",
                "Latinos",
                "Trump",
                "Trump",
                "Jeff",
                "Trump",
                "Trump",
                "Bill Clinton",
                "Bill Clinton",
                "Hillary Clinton",
                "Kathy Shelton",
                "Clinton",
                "Paula Jones",
                "Hillary",
                "Clinton",
                "Michelle Obama",
                "Khan",
                "Khan",
                "Donald",
                "Donald",
                "Obama",
                "Sidney Blumenthal",
                "Obama",
                "Michelle Obama",
                "Michelle Obama",
                "Hillary",
                "Bernie Sanders",
                "Deborah Wasserman Schultz",
                "Bernie Sanders",
                "Deborah Wasserman Schultz",
                "Clinton",
                "Donald",
                "Trump",
                "Donald Trump",
                "Clinton",
                "Clinton",
                "James Comey",
                "Martha",
                "bin Laden",
                "Hillary",
                "Clinton",
                "Clinton",
                "Donald",
                "Ken Karpowicz",
                "Ken",
                "Anderson",
                "Ken Karpowicz",
                "Affordable Care Act",
                "Clinton",
                "Donald",
                "Hillary",
                "Clinton",
                "Donald",
                "Donald",
                "Clinton",
                "Trump",
                "Obama",
                "Hillary Clinton",
                "Trump",
                "Clinton",
                "Donald",
                "Clinton",
                "Trump",
                "Hillary",
                "Hillary Clinton",
                "Obama",
                "Anderson",
                "Obama",
                "Jonathan Gruber",
                "Obama",
                "Trump",
                "Trump",
                "Trump",
                "Obama",
                "Obama",
                "Clinton",
                "Khan",
                "Donald",
                "George Washington",
                "Muhammad Ali",
                "Donald",
                "Donald",
                "Clinton",
                "Trump",
                "Donald J. Trump",
                "Khan",
                "Hillary Clinton",
                "Barack Obama",
                "Hillary Clinton",
                "Obama",
                "Clinton",
                "Donald",
                "Donald Trump",
                "Hillary Clinton",
                "Hillary Clinton",
                "Bernie Sanders",
                "Trump",
                "Clinton",
                "Clinton",
                "Tu",
                "Clinton",
                "Abraham Lincoln",
                "Steven Spielberg",
                "Lincoln",
                "Lincoln",
                "Martha",
                "Putin",
                "Donald Trump",
                "Putin",
                "Putin",
                "Donald",
                "Clinton",
                "Trump",
                "Abraham Lincoln",
                "Honest Abe",
                "Honest Abe",
                "Abraham Lincoln",
                "Putin",
                "Putin",
                "Warren Buffett",
                "Soros",
                "Trump",
                "Spencer Maass",
                "Spencer",
                "Trump",
                "Donald Trump",
                "Donald Trump",
                "Hillary",
                "Hillary Clinton",
                "Clinton",
                "Donald",
                "Bush",
                "Donald",
                "Donald",
                "Donald",
                "Buffett",
                "Warren Buffett",
                "Donald",
                "Trump",
                "Anderson",
                "Hillary",
                "Hillary Clinton",
                "Hillary Clinton",
                "Hillary",
                "Warren Buffett",
                "George Soros",
                "Hillary",
                "Anderson",
                "Bernie Sanders",
                "Obama",
                "Hillary",
                "Clinton",
                "Trump",
                "Trump",
                "Omran",
                "Bashar al-Assad",
                "Clinton",
                "Assad",
                "Putin",
                "Clinton",
                "Trump",
                "Putin",
                "Gadhafi",
                "Assad",
                "Trump",
                "Trump",
                "Assad",
                "Assad",
                "Trump",
                "Assad",
                "Kerry",
                "Obama",
                "Aleppo",
                "Aleppo",
                "Flynn",
                "George Patton",
                "Douglas MacArthur",
                "Clinton",
                "Clinton",
                "Assad",
                "Obama",
                "Martha",
                "Donald",
                "James Carter",
                "Carter",
                "Trump",
                "Trump",
                "Clinton",
                "Clinton",
                "Carter",
                "Donald",
                "Latinos",
                "Latino",
                "Trump",
                "Clinton",
                "Clinton",
                "Donald Trump",
                "Donald Trump\u2019s",
                "Carter",
                "Latinos",
                "Barack Obama",
                "Trump",
                "Girl Scout",
                "no Girl Scout",
                "Stevens",
                "Anderson",
                "Stevens",
                "Stevens",
                "Sidney Blumenthal",
                "Clinton",
                "Trump",
                "George W. Bush",
                "Obama",
                "Clinton",
                "Clinton",
                "Clinton",
                "Trump",
                "Clinton",
                "Beth Miller",
                "Clinton",
                "Donald",
                "Donald",
                "Obama",
                "Clinton",
                "Trump",
                "Scalia",
                "Scalia",
                "Hillary Clinton",
                "Hillary",
                "Hillary",
                "Clinton",
                "Ken Bone",
                "Ken",
                "Trump",
                "Obama",
                "Hillary Clinton",
                "Clinton",
                "Donald Trump",
                "Clinton",
                "Karl Becker",
                "Trump",
                "Donald",
                "Trump",
                "Hillary",
                "Thomas",
                "Chris Wallace",
                "Hillary Clinton",
                "Donald J. Trump",
                "Clinton",
                "Trump",
                "Clinton",
                "Trump",
                "Clinton",
                "Chris",
                "Obama",
                "Clinton",
                "Trump",
                "Ginsburg",
                "Trump",
                "Trump",
                "Clinton",
                "Antonin Scalia",
                "Heller",
                "Chris",
                "Trump",
                "Clinton",
                "Heller",
                "Scalia",
                "Hillary",
                "Clinton",
                "Donald",
                "Trump",
                "Hillary",
                "Trump",
                "Donald",
                "Clinton",
                "Trump",
                "Hillary",
                "Hillary",
                "Trump",
                "Clinton",
                "Trump",
                "Clinton",
                "Trump",
                "Hillary",
                "Hillary Clinton",
                "Barack Obama",
                "Trump",
                "Clinton",
                "Trump",
                "Carla",
                "Donald",
                "Donald",
                "Clinton",
                "Chris",
                "Hillary Clinton",
                "Hillary Clinton",
                "Hillary Clinton",
                "Clinton",
                "Donald",
                "Donald",
                "Trump",
                "Donald",
                "Obama",
                "Obama",
                "Obama",
                "Clinton",
                "Ronald Reagan",
                "George W. Bush",
                "Clinton",
                "Putin",
                "Chris",
                "Donald Trump",
                "Putin",
                "Putin",
                "Barack Obama",
                "Obama",
                "Putin",
                "Putin",
                "Putin",
                "Putin",
                "Vladimir Putin",
                "Putin",
                "Putin",
                "Trump-",
                "Putin",
                "Putin",
                "Putin",
                "Putin",
                "Obama",
                "Putin",
                "Donald Trump",
                "Donald",
                "Clinton",
                "Trump",
                "Clinton",
                "Bernie Sanders",
                "Donald",
                "Trump",
                "Clinton",
                "Hillary Clinton's",
                "Obama",
                "Chris",
                "Bush",
                "Obama",
                "Clinton",
                "Obama",
                "Chris",
                "Obama",
                "Bush",
                "Obama",
                "Trump",
                "Chris",
                "Donald",
                "Donald",
                "Hillary",
                "Universe",
                "Alicia Machado",
                "Osama bin",
                "Obama",
                "Trump",
                "Clinton",
                "Trump",
                "Trump",
                "Chris",
                "Clinton",
                "Donald",
                "Donald",
                "Donald",
                "Donald",
                "Trump",
                "Clinton",
                "Donald",
                "And",
                "Khan",
                "John McCain",
                "Donald",
                "Clinton",
                "Trump",
                "Clinton",
                "Trump",
                "Clintons",
                "Clinton",
                "Donald",
                "Bill",
                "Chris",
                "Buffett",
                "Soros",
                "George Soros",
                "Trump",
                "Trump",
                "Hillary",
                "Trump",
                "Hillary Clinton",
                "Pence",
                "Chris",
                "Chris",
                "Chris",
                "Donald",
                "Donald",
                "Obama",
                "Clinton",
                "Chris",
                "Trump",
                "Hillary",
                "Douglas MacArthur",
                "George Patton",
                "Donald",
                "Donald Trump",
                "Bin Laden",
                "Donald",
                "Clinton",
                "Clinton",
                "Clinton",
                "Trump",
                "John Podesta",
                "John Podesta",
                "Bernie Sanders",
                "Bernie Sanders",
                "Trump",
                "Aleppo",
                "Hillary Clinton",
                "Assad",
                "Assad",
                "Obama",
                "Assad",
                "Assad",
                "Assad",
                "Hillary",
                "Clinton",
                "Obama",
                "Joseph Dunford",
                "Clinton",
                "Chris",
                "Donald",
                "Donald",
                "Trump",
                "Putin",
                "Assad",
                "Trump",
                "Clinton",
                "Clinton",
                "Trump",
                "Trump",
                "Hillary",
                "Chris",
                "Clinton",
                "Donald",
                "Obama",
                "Reagan",
                "Reagan",
                "Donald",
                "Chris",
                "Hillary",
                "Hillary",
                "Ronald Reagan",
                "Trump",
                "Trump",
                "Clinton",
                "Chris",
                "Donald",
                "Donald",
                "Clinton",
                "Clinton",
                "Trump",
                "Latinos",
                "Latinos",
                "Barack Obama",
                "Clinton"
            ],
            "s": 668,
            "descpription": "People, including fictional"
        },
        {
            "name": "NORP",
            "content": [
                "Democratic",
                "Republican",
                "American",
                "Americans",
                "American",
                "American",
                "Americans",
                "American",
                "American",
                "Chinese",
                "American",
                "Americans",
                "Republicans",
                "Democrats",
                "Americans",
                "Americans",
                "Americans",
                "American",
                "American",
                "Americans",
                "African-Americans",
                "American",
                "Americans",
                "Hispanics",
                "African-American",
                "Hispanic",
                "African-American",
                "Hispanic",
                "African-American",
                "African-American",
                "Americans",
                "African-American",
                "African-American",
                "Democrat",
                "Americans",
                "Americans",
                "African-American",
                "American",
                "African-Americans",
                "Americans",
                "Muslims",
                "Russians",
                "Americans",
                "Republican",
                "Arab",
                "Kurdish",
                "American",
                "American",
                "American",
                "American",
                "American",
                "Iraqi",
                "Iraqi",
                "Muslim",
                "Muslims",
                "Muslims",
                "Muslim",
                "American",
                "Muslim",
                "Iranian",
                "American",
                "Democrats",
                "Republicans",
                "American",
                "Iranian",
                "American",
                "Republican",
                "Democratic",
                "Americans",
                "American",
                "Americans",
                "African-American",
                "Hispanics",
                "American",
                "Republican",
                "Republicans",
                "Americans",
                "Muslims",
                "African-Americans",
                "Hispanics",
                "African-Americans",
                "Mexican",
                "Republicans",
                "Republicans",
                "Canadians",
                "American",
                "Americans",
                "Republicans",
                "Muslims",
                "Muslim",
                "Muslims",
                "Muslims",
                "Islamic",
                "Islamic",
                "Muslim",
                "Muslims",
                "Muslims",
                "Muslims",
                "Muslims",
                "American Muslims",
                "Muslim",
                "Muslim",
                "Americans",
                "Muslims",
                "Muslim",
                "American",
                "Muslim",
                "Muslim",
                "Syrian",
                "Russian",
                "Syrian",
                "Russian",
                "Muslims",
                "Americans",
                "Russian",
                "American",
                "Russians",
                "Russians",
                "Russians",
                "Russians",
                "Americans",
                "Americans",
                "Americans",
                "Republican",
                "Democrats",
                "Republicans",
                "Republican",
                "Syrian",
                "Syrian",
                "Aleppo",
                "Iranians",
                "Russians",
                "Aleppo",
                "Russian",
                "Syrian",
                "Russians",
                "Iranian",
                "Syrians",
                "Russians",
                "American",
                "Syrian",
                "American",
                "Raqqa",
                "American",
                "American",
                "Sunnis",
                "Kurdish",
                "Kurds",
                "Kurds",
                "Kurdish",
                "Arab",
                "Americans",
                "Hispanic",
                "Americans",
                "African-American",
                "American",
                "Democrats",
                "Republicans",
                "American",
                "Americans",
                "Americans",
                "Americans",
                "African-Americans",
                "Muslims",
                "Republicans",
                "Republican",
                "African-American",
                "Americans",
                "American",
                "American",
                "Democratic",
                "Republican",
                "Americans",
                "American",
                "Americans",
                "American",
                "Mexican",
                "Mexican",
                "Mexican",
                "Americans",
                "American",
                "Brazilian",
                "Russian",
                "Americans",
                "American",
                "American",
                "Russian",
                "Russians",
                "Russian",
                "Americans",
                "American",
                "Islamic",
                "Russians",
                "American",
                "Russians",
                "Russians",
                "Chinese",
                "Chinese",
                "Chinese",
                "American",
                "American",
                "African-American",
                "American",
                "Mexican",
                "American",
                "American",
                "American",
                "American",
                "American",
                "American",
                "Chinese",
                "Republican",
                "Iraqi",
                "Kurdish",
                "Americans",
                "American",
                "American",
                "Iranians",
                "Russians",
                "Syrians",
                "Syrian",
                "Russians",
                "Sunni",
                "Iraqi",
                "Syrian",
                "Aleppo",
                "Syrian",
                "Aleppo",
                "Russian",
                "Russians",
                "Syrians",
                "Russians",
                "Syrians",
                "Aleppo",
                "American",
                "Muslim",
                "Replenish",
                "American",
                "Americans",
                "Democrats",
                "Republicans",
                "African-Americans",
                "African-Americans"
            ],
            "s": 243,
            "descpription": "Nationalities or religious or political groups"
        },
        {
            "name": "FAC",
            "content": [
                "the White House",
                "Pennsylvania Avenue",
                "Pennsylvania Avenue",
                "Madison Avenue",
                "the Bipartisan Open Debate Coalition\u2019s",
                "Pennsylvania Avenue",
                "the Great Migration",
                "Make America Great Again"
            ],
            "s": 8,
            "descpription": "Buildings, airports, highways, bridges, etc."
        },
        {
            "name": "ORG",
            "content": [
                "Hofstra University",
                "NBC",
                "Nightly News",
                "the Commission on Presidential Debates",
                "Hofstra",
                "Ford",
                "NAFTA",
                "NAFTA",
                "CROSSTALK",
                "NAFTA",
                "Senate",
                "CAFTA",
                "NAFTA",
                "NAFTA",
                "Trans-Pacific Partnership",
                "NAFTA",
                "NAFTA",
                "HillaryClinton.com",
                "ISIS",
                "ISIS",
                "ISIS",
                "ISIS",
                "Trump",
                "Fed",
                "Fed",
                "Fed",
                "Fed",
                "Fed",
                "IRS",
                "IRS",
                "IRS",
                "LaGuardia",
                "LAX",
                "the White House",
                "the Old Post Office",
                "The Trump International",
                "the Fraternal Order of Police",
                "CNN",
                "ISIS",
                "CNN",
                "the Justice Department",
                "the Justice Department",
                "the Democratic National Committee",
                "ICE",
                "ICE",
                "DNC",
                "DNC",
                "DNC",
                "Bernie Sanders",
                "ISIS",
                "ISIS",
                "ISIS",
                "ISIS",
                "ISIS",
                "ISIS",
                "ISIS",
                "Al Qaida",
                "Baghdadi",
                "ISIS",
                "ISIS",
                "ISIS",
                "ISIS",
                "ISIS",
                "ISIS",
                "ISIS",
                "NATO",
                "NATO",
                "NATO",
                "NATO",
                "NATO",
                "NATO",
                "the New York Times",
                "the New York Times",
                "the Wall Street Journal",
                "NATO",
                "NATO",
                "NATO",
                "NATO",
                "NATO",
                "ISIS",
                "ISIS",
                "ISIS",
                "Fox",
                "The AFL-CIO",
                "NATO",
                "NATO",
                "NATO",
                "Senate",
                "ISIS",
                "ISIS",
                "Washington University",
                "the University of Nevada Las Vegas",
                "Longwood University",
                "Hofstra University",
                "Patrice Brock",
                "MA",
                "Obamacare",
                "Patrice",
                "ISIS",
                "ISIS",
                "ISIS",
                "ISIS",
                "ISIS",
                "ISIS",
                "Senate",
                "FBI",
                "HillaryClinton.com",
                "FBI",
                "FBI",
                "the Senate Armed Services Committee",
                "Congress",
                "Our Justice Department",
                "Congress",
                "Congress",
                "Obamacare",
                "Obamacare",
                "Congress",
                "Obamacare",
                "Obamacare",
                "Medicaid",
                "Medicare",
                "Obamacare",
                "Bernie Sanders",
                "Obamacare",
                "Obamacare",
                "Obamacare",
                "Obamacare",
                "Medicaid",
                "Islamophobia",
                "Islamophobia",
                "the World Trade Center",
                "\u2019ve",
                "\u2019ve",
                "ISIS",
                "ISIS",
                "Islam",
                "HillaryClinton.com",
                "The Border Patrol",
                "Lincoln",
                "Congress",
                "Congress",
                "Kremlin",
                "Goldman Sachs",
                "ISIS",
                "the Old Post Office",
                "the Old Post Office",
                "the White House",
                "Congress",
                "the Old Post Office",
                "The New York Times",
                "ISIS",
                "the Children\u2019s Health Insurance Program",
                "National Guard and Reserve",
                "the State Department",
                "Assad",
                "Assad",
                "ISIS",
                "the White House",
                "Assad",
                "ISIS",
                "ISIS",
                "ISIS",
                "ISIS",
                "Assad",
                "ISIS",
                "ISIS",
                "ISIS",
                "ISIS",
                "ISIS",
                "ISIS",
                "ISIS",
                "Assad",
                "ISIS",
                "ISIS",
                "Baghdadi",
                "Al Qaida",
                "ISIS",
                "NAFTA",
                "TPP",
                "Senate",
                "the Children\u2019s Defense Fund",
                "Donald Trump\u2019s America",
                "Bernie Sanders",
                "Congress",
                "the Supreme Court",
                "Supreme Court",
                "Supreme Court",
                "the Supreme Court",
                "Citizens United",
                "the Supreme Court",
                "a Supreme Court",
                "a Supreme Court",
                "a Supreme Court",
                "a Supreme Court",
                "the Supreme Court",
                "Senate",
                "Supreme Court",
                "the Republican Party",
                "the Supreme Court",
                "EPA",
                "Environmental Protection Agency",
                "EPA",
                "HillaryClinton.com",
                "Time",
                "the Supreme Court",
                "the White House",
                "Washington University",
                "the University of Nevada",
                "the University of Nevada",
                "Fox News",
                "the Commission on Presidential Debates",
                "the Supreme Court",
                "the Supreme Court",
                "the Supreme Court",
                "a Supreme Court",
                "LGBT",
                "Citizens United",
                "the Supreme Court",
                "Citizens United",
                "the Supreme Court",
                "Senate",
                "Senate",
                "The Supreme Court",
                "a Supreme Court",
                "The Supreme Court",
                "I.C.E.",
                "Senate",
                "NAFTA",
                "ISIS",
                "NATO",
                "Kremlin",
                "NATO",
                "NATO",
                "NATO",
                "NAFTA",
                "NAFTA",
                "NAFTA",
                "Senate",
                "NAFTA",
                "Trans-Pacific Partnership",
                "Obamacare",
                "NAFTA",
                "TPP",
                "State",
                "the Trump Hotel",
                "the State Department",
                "State",
                "the State Department",
                "the Justice Department",
                "ISIS",
                "ISIS",
                "ISIS",
                "ISIS",
                "Congress",
                "FBI",
                "FBI",
                "Congress",
                "FBI",
                "Trump University",
                "ISIS",
                "Senate",
                "the Clinton Foundation",
                "Senate",
                "the Clinton Foundation",
                "the Clinton Foundation",
                "the Clinton Foundation",
                "the Clinton Foundation",
                "the Clinton Foundation",
                "the Trump Foundation",
                "The Clinton Foundation",
                "Trump Foundation",
                "The New York Times",
                "Pew",
                "FBI",
                "FBI",
                "Trump University",
                "FBI",
                "the Department of Justice",
                "ISIS",
                "ISIS",
                "the Iraqi Army",
                "ISIS",
                "Raqqa",
                "ISIS",
                "ISIS",
                "ISIS",
                "ISIS",
                "Baghdadi",
                "ISIS",
                "ISIS",
                "ISIS",
                "the Joint Chiefs of Staff",
                "ISIS",
                "ISIS",
                "the Pulse Night Club",
                "ISIS",
                "ISIS",
                "ISIS",
                "Committee for a Responsible Federal Budget",
                "the New York Times",
                "Time",
                "Responsible Federal Budget",
                "Medicare",
                "Social Security",
                "Medicare and Social Security",
                "Obamacare",
                "Obamacare",
                "Obamacare",
                "Obamacare",
                "Obamacare",
                "Social Security",
                "Medicare",
                "Social Security Trust",
                "Social Security",
                "Social Security",
                "Social Security",
                "Medicare",
                "Medicare",
                "the Commission of Presidential Debates"
            ],
            "s": 283,
            "descpription": "Numerals that do not fall under another type"
        },
        {
            "name": "GPE",
            "content": [
                "Hempstead",
                "New York",
                "America",
                "America",
                "the United States",
                "the United States",
                "America",
                "Lester",
                "Mexico",
                "China",
                "China",
                "Mexico",
                "the United States",
                "Michigan",
                "Ohio",
                "the United States",
                "Indianapolis",
                "Mexico",
                "China",
                "Mexico",
                "Mexico",
                "Lester",
                "Mexico",
                "Michigan",
                "Ohio",
                "America",
                "America",
                "China",
                "Ohio",
                "Pennsylvania",
                "Lester",
                "Lester",
                "America",
                "America",
                "Newark",
                "Dubai",
                "Qatar",
                "China",
                "the United States",
                "the United States",
                "the United States",
                "America",
                "Charlotte",
                "Tulsa",
                "Tulsa",
                "Charlotte",
                "Charlotte",
                "the United States",
                "Chicago",
                "Chicago",
                "Chicago",
                "Chicago",
                "New York",
                "New York",
                "Chicago",
                "Chicago",
                "Chicago",
                "Chicago",
                "Chicago",
                "Dallas",
                "Lester",
                "NRA",
                "New York City",
                "New York City",
                "New York",
                "New York",
                "Detroit",
                "Philadelphia",
                "the United States",
                "Kenya",
                "Brooklyn",
                "Queens",
                "Palm Beach",
                "Florida",
                "Russia",
                "Russia",
                "Russia",
                "China",
                "Iran",
                "the United States",
                "Russia",
                "Russia",
                "Russia",
                "Russia",
                "Russia",
                "China",
                "Russia",
                "China",
                "Lester",
                "Raqqa",
                "Iraq",
                "Iraq",
                "Syria",
                "New York",
                "New Jersey",
                "Minnesota",
                "San Bernardino",
                "Orlando",
                "Iraq",
                "Libya",
                "Iraq",
                "Wrong",
                "Libya",
                "Iraq",
                "Iraq",
                "Lester",
                "the United States",
                "New York",
                "Minnesota",
                "New Jersey",
                "Iran",
                "Lester",
                "Iraq",
                "Iraq",
                "Iraq",
                "Iraq",
                "Afghanistan",
                "Iran",
                "Iran",
                "Iran",
                "Russia",
                "China",
                "Iran",
                "Iran",
                "Iran",
                "Japan",
                "South Korea",
                "Saudi Arabia",
                "the United States",
                "Wrong",
                "Japan",
                "Germany",
                "South Korea",
                "Saudi Arabia",
                "Japan",
                "America",
                "Russia",
                "Russia",
                "North Korea",
                "China",
                "China",
                "North Korea",
                "China",
                "North Korea",
                "Iran",
                "Iran",
                "Iran",
                "North Korea",
                "Iran",
                "North Korea",
                "Yemen",
                "Iran",
                "Japan",
                "South Korea",
                "America",
                "Iran",
                "Iran",
                "Lester",
                "Japan",
                "Lester",
                "Japan",
                "Saudi Arabia",
                "Saudi Arabia",
                "Iran",
                "Iran",
                "Lester",
                "U.S.",
                "America",
                "America",
                "St. Louis",
                "Farmville",
                "Virginia",
                "America",
                "America",
                "Iran",
                "America",
                "America",
                "America",
                "America",
                "America",
                "America",
                "America",
                "America",
                "New York",
                "New York",
                "United States",
                "Ohio",
                "Iraq",
                "Indiana",
                "the United States of America",
                "the United States",
                "the United States",
                "the United States",
                "Canada",
                "the United States",
                "Gorbah Hamed",
                "the United States",
                "San Bernardino",
                "Orlando",
                "Paris",
                "the United States Army",
                "America",
                "America",
                "America",
                "America",
                "America",
                "America",
                "the United States",
                "Iraq",
                "Iraq",
                "Syria",
                "Trojan",
                "Syria",
                "Iraq",
                "Iraq",
                "the United States",
                "Virginia",
                "Moscow",
                "Russia",
                "Russia",
                "Russia",
                "Russia",
                "Russia",
                "Russia",
                "Russia",
                "Russia",
                "United States",
                "Russia",
                "United States",
                "United States",
                "United States",
                "China",
                "Libya",
                "Syria",
                "Iraq",
                "Iraq",
                "New York",
                "New York",
                "Russia",
                "New York",
                "Washington",
                "Syria",
                "Syria",
                "Russia",
                "Pennsylvania",
                "Syria",
                "U.S.",
                "Syria",
                "Russia",
                "Russia",
                "Russia",
                "Syria",
                "the United States",
                "Russia",
                "Russia",
                "Iran",
                "Russia",
                "Russia",
                "Iraq",
                "Libya",
                "Russia",
                "Russia",
                "Russia",
                "Iran",
                "Iran",
                "Iran",
                "Russia",
                "Russia",
                "Iran",
                "Syria",
                "Russia",
                "Russia",
                "the United States of America",
                "Syria",
                "Syria",
                "Syria",
                "Syria",
                "Russia",
                "Iran",
                "Syria",
                "Mosul",
                "Mosul",
                "Mosul",
                "Washington",
                "Iraq",
                "Mosul",
                "Mosul",
                "Mosul",
                "Mosul",
                "Mosul",
                "Iraq",
                "Mosul",
                "U.S.",
                "Syria",
                "Iraq",
                "Iraq",
                "Mosul",
                "Syria",
                "Iraq",
                "Iraq",
                "the United States",
                "the United States",
                "New York",
                "Texas",
                "Ethiopia",
                "Ethiopia",
                "Charlotte",
                "Baltimore",
                "Chicago",
                "Washington",
                "Benghazi",
                "China",
                "the United States",
                "West Virginia",
                "Ohio",
                "Pennsylvania",
                "China",
                "the United States",
                "China",
                "Las Vegas",
                "Las Vegas",
                "Arkansas",
                "New York",
                "the District of Columbia",
                "D.C.",
                "NRA",
                "Chicago",
                "the United States",
                "NRA",
                "America",
                "United States",
                "China",
                "Romania",
                "New Hampshire",
                "Las Vegas",
                "Phoenix",
                "United States",
                "Mexico",
                "Mexico",
                "Mexico",
                "Wikileaks",
                "Syria",
                "Russia",
                "the United States",
                "the United States",
                "the United States of America",
                "Russia",
                "China",
                "Syria",
                "Russia",
                "Russia",
                "Russia",
                "the United States",
                "Russia",
                "Syria",
                "Wrong",
                "Japan",
                "Korea",
                "Saudi Arabia",
                "Japan",
                "Saudi Arabia",
                "Japan",
                "Germany",
                "South Korea",
                "The United States",
                "United States",
                "America",
                "Japan",
                "Germany",
                "South Korea",
                "Saudi Arabia",
                "Saudi Arabia",
                "Japan",
                "Germany",
                "South Korea",
                "Pennsylvania",
                "Ohio",
                "Florida",
                "New York",
                "Mexico",
                "India",
                "China",
                "China",
                "Vietnam",
                "Mexico",
                "Mexico",
                "China",
                "China",
                "Las Vegas",
                "Arkansas",
                "Beijing",
                "Syria",
                "Libya",
                "Iraq",
                "Iraq",
                "the United States",
                "Chicago",
                "Chicago",
                "America",
                "America",
                "the United States",
                "the United States",
                "Wrong",
                "Indiana",
                "America",
                "Haiti",
                "Saudi Arabia",
                "Qatar",
                "Haiti",
                "Florida",
                "Haiti",
                "Haiti",
                "Haiti",
                "Haiti",
                "Haiti",
                "Haiti",
                "Haiti",
                "Palm Beach",
                "Palm Beach",
                "America",
                "United States",
                "Iowa",
                "Wisconsin",
                "Arizona",
                "Mosul",
                "Iraq",
                "U.S.",
                "Iraq",
                "Mosul",
                "Syria",
                "Syria",
                "Syria",
                "Mosul",
                "Iraq",
                "U.S.",
                "Mosul",
                "Mosul",
                "Mosul",
                "Mosul",
                "Mosul",
                "Mosul",
                "Mosul",
                "Mosul",
                "Mosul",
                "Mosul",
                "Mosul",
                "Migration",
                "Mosul",
                "Mosul",
                "Mosul",
                "Iran",
                "Iran",
                "Iran",
                "Iran",
                "Iran",
                "Iraq",
                "Mosul",
                "Iran",
                "Mosul",
                "Iraq",
                "Iraq",
                "Iraq",
                "Iraq",
                "Iran",
                "Iraq",
                "Wrong",
                "Wrong",
                "Iraq",
                "Iraq",
                "Wrong",
                "Mosul",
                "Mosul",
                "Syria",
                "Mosul",
                "Mosul",
                "Syria",
                "Mosul",
                "Iran",
                "Iran",
                "Iraq",
                "Wikileaks",
                "Mosul",
                "America",
                "Syria",
                "Russia",
                "Russia",
                "Iran",
                "Russia",
                "Iran",
                "Russia",
                "Iran",
                "Trojan",
                "Syria",
                "Russia",
                "Syria",
                "Syria",
                "Syria",
                "Orlando",
                "Queens",
                "Syria",
                "Iraq",
                "United States",
                "Russia",
                "Syria",
                "Russia",
                "Iran",
                "China",
                "America",
                "America",
                "America",
                "America",
                "America",
                "Las Vegas"
            ],
            "s": 514,
            "descpription": "Countries, cities, states"
        },
        {
            "name": "LOC",
            "content": [
                "New England",
                "the Middle East",
                "the Middle East",
                "Europe",
                "Securing America",
                "Europe",
                "Europe",
                "the Middle East",
                "the Middle East",
                "the Middle East",
                "the Middle East",
                "the Middle East",
                "Sean Hannity",
                "the Middle East",
                "East Asia",
                "the Middle East",
                "San Bernardino",
                "Gulf",
                "Europe",
                "the Middle East",
                "the Middle East",
                "the Middle East",
                "the Middle East",
                "the Middle East",
                "the Middle East",
                "Asia",
                "Asia",
                "Europe",
                "the Middle East",
                "Little Haiti",
                "Earth"
            ],
            "s": 31,
            "descpription": "Non-GPE locations, mountain ranges, bodies of water"
        }
    ]

